<template>
  <div class="fixed top-0 w-full h-full flex items-center justify-center bg-white opacity-80 z-50">
    <div class="loadingio-spinner-rolling-4d852zheoeo"><div class="ldio-kwngnvn4gw">
      <div></div>
    </div></div>
  </div>
</template>

<script>
export default {
  name: "Loading"
}
</script>

<style type="text/css">
@keyframes ldio-kwngnvn4gw {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-kwngnvn4gw div {
  position: absolute;
  width: 30px;
  height: 30px;
  border: 2px solid #49cbfb;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-kwngnvn4gw div {
  animation: ldio-kwngnvn4gw 1.0526315789473684s linear infinite;
  top: 100px;
  left: 100px
}
.loadingio-spinner-rolling-4d852zheoeo {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-kwngnvn4gw {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-kwngnvn4gw div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>